Бачище: Задача 1. Инициализация рабочего окружения #1
bachisheo/formal-lang-course pull request #1
Opened 2023-02-25 19:18 UTC by bachisheo

Реализован весь функционал из задания, добавлены тесты.

2023-02-26 19:01 UTC, rustam-azimov requested changes

2023-02-26 19:01 UTC, rustam-azimov commented on project/graph_utils.py
> +def number_of_nodes(graph: nx.MultiDiGraph) -> int:
Эти функции также надо вызвать в одной, и вернуть named tuple

2023-02-26 21:12 UTC, bachisheo commented on project/graph_utils.py
> +def number_of_nodes(graph: nx.MultiDiGraph) -> int:
Как раз об этом спрашивала в чатике, но наверно не так сформулировала. Исправлено.

2023-02-27 05:41 UTC, rustam-azimov approved these changes

2023-03-02 19:08 UTC, merged