Задача 3. Регулярные запросы для всех пар вершин
bachisheo/formal-lang-course pull request #3
Opened 2023-03-10 19:13 UTC by bachisheo

1. Реализована функция пересечения двух конечных автоматов через тензорное произведение.
2. Реализована функция выполнения регулярных запросов к графам: по графу с заданными стартовыми и финальными вершинами и регулярному выражению вернуть те пары вершин из заданных стартовых и финальных, которые связанны путём, формирующем слово из языка, задаваемого регулярным выражением.
3. Добавлены тесты

2023-03-11 20:28 UTC, rustam-azimov requested changes

2023-03-11 20:28 UTC, rustam-azimov commented on project/rpq_utils.py
> +def start_final_states_rpq(bd: EpsilonNFA, query: fa.Regex):
Добавьте также функцию, которая принимает граф, стартовые и начальные вершины и регулярное выражение.

2023-03-12 23:59 UTC, bachisheo commented on project/rpq_utils.py
> +def start_final_states_rpq(bd: EpsilonNFA, query: fa.Regex):
Добавлено
Заметила ошибку в предыдущем решении, связанную с построением автомата по графу. Исправила и покрыла доп тестами

2023-03-14 13:03 UTC, rustam-azimov approved these changes

2023-03-14 16:00 UTC, merged